### ISSUE TITLE
false positive result

### ISSUE THREAD

**Issue by fordrink** [rzizah/private-nuclei-template#1]
I got so many false positives here, do you have any solution?
![2024-04-21_01-56](https://github.com/rzizah/private-nuclei-template/assets/74085414/6a320aa2-31cd-479e-80e2-f21c5d709444)
![2024-04-21_01-59](https://github.com/rzizah/private-nuclei-template/assets/74085414/c889095a-14ef-4e50-9025-0c8d984c01c5)

**Comment by rzizah** [comment]
it's because the status code; will add a new matcher for status 200 
check the new added one, can you confirm it has less false positive rate.

**Comment by fordrink** [comment]
Thanks.
